#!/usr/bin/env python3
"""
Generate SVG infographics for financial topics.
Creates visual diagrams that complement social media posts.
"""

import argparse
from pathlib import Path
from datetime import datetime

class SVGGenerator:
    """Generate SVG diagrams for financial education."""

    def __init__(self, width=1200, height=800):
        self.width = width
        self.height = height

    def create_svg(self, content: str) -> str:
        """Wrap content in SVG container."""
        return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.width} {self.height}" width="{self.width}" height="{self.height}">
  <defs>
    <style>
      .title {{ font-size: 48px; font-weight: bold; fill: #1a365d; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
      .subtitle {{ font-size: 28px; fill: #2d3748; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
      .label {{ font-size: 20px; fill: #4a5568; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
      .value {{ font-size: 32px; font-weight: bold; fill: #2b6cb0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
      .box {{ fill: #e6f2ff; stroke: #2b6cb0; stroke-width: 2; }}
      .box-title {{ font-size: 22px; font-weight: bold; fill: #2b6cb0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
      .highlight {{ fill: #f6ad55; }}
      .check {{ fill: #48bb78; }}
      .arrow {{ stroke: #4a5568; stroke-width: 3; fill: none; marker-end: url(#arrowhead); }}
      .comparison-text {{ font-size: 18px; fill: #2d3748; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}
    </style>
    <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto">
      <polygon points="0 0, 10 3, 0 6" fill="#4a5568" />
    </marker>
  </defs>

  <!-- Background -->
  <rect width="{self.width}" height="{self.height}" fill="#ffffff"/>

{content}

  <!-- Footer -->
  <text x="50" y="{self.height - 20}" class="label" font-size="16">Generated by Financial Advisor Content Hub</text>
</svg>'''

    def life_cover_protection_gap(self) -> str:
        """Life cover protection gap visualization."""
        svg = '''
  <!-- Title -->
  <text x="600" y="60" class="title" text-anchor="middle">Protection Gap Analysis</text>

  <!-- Left side: Without Life Cover -->
  <rect x="80" y="120" width="400" height="600" class="box"/>
  <text x="280" y="160" class="box-title" text-anchor="middle">Without Life Cover</text>

  <!-- Icons and text for without -->
  <circle cx="280" cy="240" r="40" fill="#ff6b6b"/>
  <text x="280" y="250" text-anchor="middle" fill="white" font-size="20">✗</text>
  <text x="280" y="330" class="comparison-text" text-anchor="middle">Family loses</text>
  <text x="280" y="360" class="comparison-text" text-anchor="middle">main income</text>

  <circle cx="280" cy="450" r="40" fill="#ff6b6b"/>
  <text x="280" y="460" text-anchor="middle" fill="white" font-size="20">✗</text>
  <text x="280" y="540" class="comparison-text" text-anchor="middle">Debt burden</text>
  <text x="280" y="570" class="comparison-text" text-anchor="middle">remains</text>

  <circle cx="280" cy="660" r="40" fill="#ff6b6b"/>
  <text x="280" y="670" text-anchor="middle" fill="white" font-size="20">✗</text>
  <text x="280" y="730" class="comparison-text" text-anchor="middle">Future plans</text>
  <text x="280" y="760" class="comparison-text" text-anchor="middle">derailed</text>

  <!-- Right side: With Life Cover -->
  <rect x="720" y="120" width="400" height="600" class="box" fill="#e6ffe6" stroke="#48bb78"/>
  <text x="920" y="160" class="box-title" text-anchor="middle" fill="#48bb78">With Life Cover</text>

  <!-- Icons and text for with -->
  <circle cx="920" cy="240" r="40" fill="#48bb78"/>
  <text x="920" y="250" text-anchor="middle" fill="white" font-size="24">✓</text>
  <text x="920" y="330" class="comparison-text" text-anchor="middle">Family protected</text>
  <text x="920" y="360" class="comparison-text" text-anchor="middle">financially</text>

  <circle cx="920" cy="450" r="40" fill="#48bb78"/>
  <text x="920" y="460" text-anchor="middle" fill="white" font-size="24">✓</text>
  <text x="920" y="540" class="comparison-text" text-anchor="middle">Debts covered</text>
  <text x="920" y="570" class="comparison-text" text-anchor="middle">paid off</text>

  <circle cx="920" cy="660" r="40" fill="#48bb78"/>
  <text x="920" y="670" text-anchor="middle" fill="white" font-size="24">✓</text>
  <text x="920" y="730" class="comparison-text" text-anchor="middle">Dreams stay</text>
  <text x="920" y="760" class="comparison-text" text-anchor="middle">on track</text>

  <!-- Arrow between -->
  <path d="M 520 420 L 680 420" class="arrow"/>
'''
        return self.create_svg(svg)

    def income_protection_benefit(self) -> str:
        """Income Protection benefit stages."""
        svg = '''
  <!-- Title -->
  <text x="600" y="60" class="title" text-anchor="middle">Income Protection Journey</text>

  <!-- Stage 1: Working -->
  <rect x="100" y="150" width="220" height="200" class="box"/>
  <text x="210" y="190" class="box-title" text-anchor="middle">Stage 1</text>
  <text x="210" y="220" class="subtitle" text-anchor="middle" font-size="20">Working</text>
  <circle cx="210" cy="290" r="30" fill="#4299e1"/>
  <text x="210" y="300" text-anchor="middle" fill="white" font-size="24">💼</text>
  <text x="210" y="340" class="comparison-text" text-anchor="middle">Earning full</text>
  <text x="210" y="365" class="comparison-text" text-anchor="middle">income</text>

  <!-- Arrow -->
  <path d="M 340 250 L 400 250" class="arrow"/>

  <!-- Stage 2: Injured/Ill -->
  <rect x="430" y="150" width="220" height="200" class="box" fill="#fff5e6"/>
  <text x="540" y="190" class="box-title" text-anchor="middle" fill="#f6ad55">Stage 2</text>
  <text x="540" y="220" class="subtitle" text-anchor="middle" font-size="20" fill="#f6ad55">Injury/Illness</text>
  <circle cx="540" cy="290" r="30" fill="#f6ad55"/>
  <text x="540" y="300" text-anchor="middle" fill="white" font-size="24">🏥</text>
  <text x="540" y="340" class="comparison-text" text-anchor="middle">Can't work</text>
  <text x="540" y="365" class="comparison-text" text-anchor="middle">temporarily</text>

  <!-- Arrow -->
  <path d="M 670 250 L 730 250" class="arrow"/>

  <!-- Stage 3: Protected -->
  <rect x="760" y="150" width="220" height="200" class="box" fill="#e6ffe6"/>
  <text x="870" y="190" class="box-title" text-anchor="middle" fill="#48bb78">Stage 3</text>
  <text x="870" y="220" class="subtitle" text-anchor="middle" font-size="20" fill="#48bb78">Protected</text>
  <circle cx="870" cy="290" r="30" fill="#48bb78"/>
  <text x="870" y="300" text-anchor="middle" fill="white" font-size="24">💰</text>
  <text x="870" y="340" class="comparison-text" text-anchor="middle">Income benefit</text>
  <text x="870" y="365" class="comparison-text" text-anchor="middle">paid out</text>

  <!-- Arrow -->
  <path d="M 1000 250 L 1060 250" class="arrow"/>

  <!-- Stage 4: Recovery -->
  <rect x="1090" y="150" width="220" height="200" class="box"/>
  <text x="1200" y="190" class="box-title" text-anchor="middle">Stage 4</text>
  <text x="1200" y="220" class="subtitle" text-anchor="middle" font-size="20">Recovery</text>
  <circle cx="1200" cy="290" r="30" fill="#4299e1"/>
  <text x="1200" y="300" text-anchor="middle" fill="white" font-size="24">✓</text>
  <text x="1200" y="340" class="comparison-text" text-anchor="middle">Back to work</text>
  <text x="1200" y="365" class="comparison-text" text-anchor="middle">protected</text>

  <!-- Key Metric -->
  <rect x="400" y="450" width="400" height="200" fill="#f0f8ff" stroke="#2b6cb0" stroke-width="3" rx="10"/>
  <text x="600" y="510" class="subtitle" text-anchor="middle">Average Claim Duration</text>
  <text x="600" y="580" class="value" text-anchor="middle">45 Days - 3 Years</text>
  <text x="600" y="630" class="comparison-text" text-anchor="middle">Without protection, many families face</text>
  <text x="600" y="655" class="comparison-text" text-anchor="middle">financial hardship within weeks</text>
'''
        return self.create_svg(svg)

    def affordability_breakdown(self) -> str:
        """Affordability breakdown by expense."""
        svg = '''
  <!-- Title -->
  <text x="600" y="60" class="title" text-anchor="middle">Monthly Expense Breakdown</text>

  <!-- Pie chart representation using bars -->
  <text x="100" y="150" class="subtitle">Your Monthly Budget</text>

  <!-- Housing -->
  <rect x="100" y="180" width="800" height="60" fill="#4299e1"/>
  <text x="120" y="215" class="comparison-text" fill="white">Housing (35%)</text>
  <text x="920" y="215" class="value">£1,050</text>

  <!-- Food -->
  <rect x="100" y="260" width="400" height="60" fill="#2d3748"/>
  <text x="120" y="295" class="comparison-text" fill="white">Food & Groceries (18%)</text>
  <text x="920" y="295" class="value">£540</text>

  <!-- Utilities -->
  <rect x="100" y="340" width="280" height="60" fill="#718096"/>
  <text x="120" y="375" class="comparison-text" fill="white">Utilities (12%)</text>
  <text x="920" y="375" class="value">£360</text>

  <!-- Transportation -->
  <rect x="100" y="420" width="320" height="60" fill="#a0aec0"/>
  <text x="120" y="455" class="comparison-text" fill="white">Transportation (14%)</text>
  <text x="920" y="455" class="value">£420</text>

  <!-- Protection (Insurance) -->
  <rect x="100" y="500" width="120" height="60" fill="#48bb78"/>
  <text x="110" y="535" class="comparison-text" fill="white">Protection (5%)</text>
  <text x="920" y="535" class="value">£150</text>

  <!-- Other -->
  <rect x="100" y="580" width="160" height="60" fill="#f6ad55"/>
  <text x="110" y="615" class="comparison-text" fill="white">Other (16%)</text>
  <text x="920" y="615" class="value">£480</text>

  <!-- Total -->
  <rect x="100" y="660" width="1000" height="80" fill="#1a365d"/>
  <text x="120" y="700" class="value" fill="white" font-size="36">Total Monthly Income Needed: £3,000</text>
  <text x="120" y="735" class="comparison-text" fill="white">Income Protection covers 5% - Keep the other 95% safe</text>
'''
        return self.create_svg(svg)

    def risk_timeline(self) -> str:
        """Risk and life events timeline."""
        svg = '''
  <!-- Title -->
  <text x="600" y="60" class="title" text-anchor="middle">Life Events & Protection Timeline</text>

  <!-- Timeline line -->
  <line x1="150" y1="250" x2="1150" y2="250" stroke="#4a5568" stroke-width="3"/>

  <!-- Age 25 -->
  <circle cx="200" cy="250" r="15" fill="#4299e1"/>
  <text x="200" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Age 25</text>
  <text x="200" y="360" class="comparison-text" text-anchor="middle">First job</text>
  <text x="200" y="385" class="comparison-text" text-anchor="middle">Start protecting</text>

  <!-- Age 30 -->
  <circle cx="450" cy="250" r="15" fill="#4299e1"/>
  <text x="450" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Age 30</text>
  <text x="450" y="360" class="comparison-text" text-anchor="middle">Marriage/</text>
  <text x="450" y="385" class="comparison-text" text-anchor="middle">Partnership</text>

  <!-- Age 35 -->
  <circle cx="700" cy="250" r="15" fill="#f6ad55"/>
  <text x="700" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Age 35</text>
  <text x="700" y="360" class="comparison-text" text-anchor="middle">Children</text>
  <text x="700" y="385" class="comparison-text" text-anchor="middle">Increase coverage</text>

  <!-- Age 45 -->
  <circle cx="950" cy="250" r="15" fill="#f6ad55"/>
  <text x="950" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Age 45</text>
  <text x="950" y="360" class="comparison-text" text-anchor="middle">Peak earning</text>
  <text x="950" y="385" class="comparison-text" text-anchor="middle">Peak risk years</text>

  <!-- Age 55 -->
  <circle cx="1100" cy="250" r="15" fill="#48bb78"/>
  <text x="1100" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Age 55</text>
  <text x="1100" y="360" class="comparison-text" text-anchor="middle">Retirement</text>
  <text x="1100" y="385" class="comparison-text" text-anchor="middle">planning</text>

  <!-- Key message -->
  <rect x="300" y="500" width="600" height="150" fill="#e6f2ff" stroke="#2b6cb0" stroke-width="2" rx="10"/>
  <text x="600" y="550" class="subtitle" text-anchor="middle">💡 Key Insight</text>
  <text x="600" y="605" class="comparison-text" text-anchor="middle">Protection needs change throughout life.</text>
  <text x="600" y="635" class="comparison-text" text-anchor="middle">Review your coverage every 3-5 years or after major life events.</text>
'''
        return self.create_svg(svg)

    def funeral_benefit_support(self) -> str:
        """Funeral benefit support visualization."""
        svg = '''
  <!-- Title -->
  <text x="600" y="60" class="title" text-anchor="middle">Funeral Benefit: What It Covers</text>

  <!-- Funeral costs breakdown -->
  <text x="100" y="150" class="subtitle">Typical Funeral Expenses</text>

  <!-- Coffin -->
  <rect x="100" y="180" width="300" height="50" fill="#4299e1"/>
  <text x="110" y="212" class="comparison-text" fill="white">Coffin & Burial</text>
  <text x="410" y="212" class="value">£2,000</text>

  <!-- Service -->
  <rect x="100" y="240" width="350" height="50" fill="#4299e1"/>
  <text x="110" y="272" class="comparison-text" fill="white">Service & Flowers</text>
  <text x="460" y="272" class="value">£2,500</text>

  <!-- Transport -->
  <rect x="100" y="300" width="250" height="50" fill="#4299e1"/>
  <text x="110" y="332" class="comparison-text" fill="white">Transport</text>
  <text x="360" y="332" class="value">£1,500</text>

  <!-- Catering -->
  <rect x="100" y="360" width="300" height="50" fill="#4299e1"/>
  <text x="110" y="392" class="comparison-text" fill="white">Reception/Catering</text>
  <text x="410" y="392" class="value">£2,000</text>

  <!-- Total -->
  <rect x="100" y="420" width="600" height="80" fill="#1a365d"/>
  <text x="120" y="465" class="value" fill="white" font-size="32">Average Total Cost</text>
  <text x="120" y="495" class="subtitle" fill="#f6ad55" font-size="40">£8,000 - £10,000</text>

  <!-- Key message -->
  <rect x="800" y="180" width="350" height="400" fill="#e6ffe6" stroke="#48bb78" stroke-width="3" rx="10"/>
  <text x="975" y="230" class="box-title" text-anchor="middle" fill="#48bb78">Funeral Benefit</text>
  <text x="975" y="280" class="value" text-anchor="middle" fill="#48bb78">£3,000-£10,000</text>

  <text x="975" y="330" class="comparison-text" text-anchor="middle" font-weight="bold">Covers:</text>

  <circle cx="830" cy="370" r="6" fill="#48bb78"/>
  <text x="850" y="375" class="comparison-text">Funeral costs</text>

  <circle cx="830" cy="410" r="6" fill="#48bb78"/>
  <text x="850" y="415" class="comparison-text">Final expenses</text>

  <circle cx="830" cy="450" r="6" fill="#48bb78"/>
  <text x="850" y="455" class="comparison-text">Estate duties</text>

  <circle cx="830" cy="490" r="6" fill="#48bb78"/>
  <text x="850" y="495" class="comparison-text">Peace of mind</text>

  <circle cx="830" cy="530" r="6" fill="#48bb78"/>
  <text x="850" y="535" class="comparison-text">No burden on family</text>
'''
        return self.create_svg(svg)

    def generate(self, topic: str, angle: str = "general") -> str:
        """Generate appropriate infographic based on topic."""

        topic_lower = topic.lower()
        angle_lower = angle.lower()

        # Map topics to visualization functions
        diagrams = {
            'life-cover': {
                'benefit': self.life_cover_protection_gap,
                'misconception': self.life_cover_protection_gap,
                'default': self.life_cover_protection_gap,
            },
            'income-protector': {
                'benefit': self.income_protection_benefit,
                'scenario': self.income_protection_benefit,
                'statistic': self.income_protection_benefit,
                'default': self.income_protection_benefit,
            },
            'funeral-benefit': {
                'benefit': self.funeral_benefit_support,
                'default': self.funeral_benefit_support,
            },
            'affordability': {
                'default': self.affordability_breakdown,
            },
        }

        # Find matching diagram function
        for key, angle_map in diagrams.items():
            if key in topic_lower:
                func = angle_map.get(angle_lower, angle_map.get('default'))
                if func:
                    return func()

        # Fallback to timeline for any other topic
        return self.risk_timeline()


def save_infographic(svg_content: str, filename: Path) -> None:
    """Save SVG to file."""
    filename.parent.mkdir(parents=True, exist_ok=True)
    with open(filename, 'w') as f:
        f.write(svg_content)


def main():
    parser = argparse.ArgumentParser(description="Generate financial infographics")
    parser.add_argument('--topic', required=True, help="Topic slug (e.g., 'life-cover')")
    parser.add_argument('--angle', default='general', help="Post angle (benefit, misconception, etc)")
    parser.add_argument('--output-dir', default='/Users/kennedysigauke/Work/Personal/financial-advisor/docs/posts')

    args = parser.parse_args()

    # Generate SVG
    generator = SVGGenerator()
    svg = generator.generate(args.topic, args.angle)

    # Determine filename (use today's date and topic)
    today = datetime.now().strftime("%Y-%m-%d")
    infographic_dir = Path(args.output_dir) / "infographics"
    filename = infographic_dir / f"{today}_{args.topic}.svg"

    # Save
    save_infographic(svg, filename)

    print(f"✅ Infographic generated: {filename}")
    print(f"   Topic: {args.topic}")
    print(f"   Angle: {args.angle}")
    print(f"   Size: 1200x800px")


if __name__ == "__main__":
    main()
